before_script:
    - pod install

deploy_project:
    stage: deploy
    only:
        refs:
            - master
    script:
        - xcodebuild clean -project Chatter.xcodeproj -scheme Chatter
        - echo Hello World!
    tags:
        - macbookpro.nick